name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - Db3center
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - Db3center

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_OCEAN_0819CA510 }}
          action: "upload"
          app_location: "."  # Corrigido:  "." para indicar a raiz do repositório.
          skip_app_build: true # Importante: Pula o build, essencial para apenas index.html


  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_OCEAN_0819CA510 }}
          action: "close"
